config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('youtube.urls'))

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

youtube/urls.py
from django.urls import path
from youtube.views.views import *
from youtube.views.profile_view import *
from youtube.views.registration_view import *
from youtube.views.subcrib_view import *
from youtube.s3.decode_file import stream_video
from youtube.views.dislike_like_views import *
from youtube.views.notificate_views import notificated_view

urlpatterns = [
    # Class View
    path("", Home.as_view(), name="home"),
    path("video/<slug:slug>/", VideoDetail.as_view(), name="video_detail"),
    path("profile/<slug:slug>/", Profile.as_view(), name="profile"),
    path("profile_settings/<slug:slug>/", ProfileSettings.as_view(), name="profile_settings"),
    path("watch_later_list/<slug:slug>/", WatchLaterList.as_view(), name="watch_later_list"),
    path("liked_video_list/<slug:slug>/", LikeVideoList.as_view(), name="likes_list"),
    path("update/<slug:slug>/", EditText.as_view(), name="edit_video"),
    path("update/<slug:slug>/photo/", EditPhoto.as_view(), name="edit_only_photo"),
    path("update/<slug:slug>/comment", CommentUpdate.as_view(), name="comment_update"),
    path("delete/<slug:slug>/comment", CommentDelete.as_view(), name="comment_delete"),
    path("subs/<slug:slug>/", Subs.as_view(), name="subs"),
    path("search/", SearchResults.as_view(), name="search"),

    # path("createvideo/", CreateView.as_view(), name="createvideo"),

    # Func View
    path("createvideo/", create_video, name="createvideo"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("register/", register, name="register"),
    path("stream/<slug:video_slug>/", stream_video, name="stream_video"),
    path('video/<slug:slug>/like/', like_video, name='like_video'),
    path('video/<slug:slug>/dislike/', dislike_video, name='dislike_video'),
    path('video/<slug:slug>/vote/<str:value>/', post_vote, name='video_vote'),
    path('notificated/', notificated_view, name='notificated'),
    path('watch_later/<slug:video_slug>/', toggle_watch_later, name="watch_later"),
    path('share_video/<slug:video_slug>/', share_link, name="share_link"),
    path("add_play_list/<slug:video_slug>/", add_play_list, name="add_play_list"),
    path("delete_video_playlist/<slug:play_list_slug>/<slug:video_slug>/", delete_from_play_list, name="delete_from_play_list"),
    path("add_from_play_list/<slug:play_list_slug>/<slug:video_slug>/", add_from_play_list,
         name="add_from_play_list"),
    path("add_comment/<slug:slug>/", add_comment, name="add_comment"),
    path("add_subscribers/<int:autor_pk>/", add_subscribers, name="add_subscribers"),
    path("remove_subscribers/<int:autor_pk>/", remove_subscribers, name="remove_subscribers"),
    path("comment/<int:comment_id>/vote/<str:value>/", comment_vote, name="comment_vote"),
    path("comment/<int:comment_id>/like/", comment_like, name="comment_like"),
    path("comment/<int:comment_id>/dislike/", comment_dislike, name="comment_dislike"),

]

youtube/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
import uuid
# Create your models here.


def generate_random_slug():
    return uuid.uuid4().hex[:8]

class Autor(models.Model):
    slug = models.SlugField(unique=True, null=True, blank=True, default=generate_random_slug)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="autor")
    avatar = models.URLField(max_length=500)
    pseudonym = models.CharField(max_length=100, blank=True, null=True)
    nickname = models.CharField(max_length=100, unique=True, blank=True, null=True)
    desc = models.TextField(max_length=600, blank=True, null=True)
    data = models.DateField(blank=True, null=True)
    subscribers = models.ManyToManyField(User, related_name="following", blank=True)
    subscriptions = models.ManyToManyField(User, related_name="follow", blank=True)
    photo = models.ImageField(upload_to='autors/photos/', blank=True, null=True)
    banner = models.ImageField(upload_to='autors/banners/', blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    email = models.EmailField(unique=True, blank=True, null=True)

    def __str__(self):
        return f"{self.nickname}"

    def subscriber_count(self):
        return self.subscribers.count()

    def subscription_count(self):
        return self.subscriptions.count()


class Video(models.Model):
    slug = models.SlugField(unique=True, null=True, blank=True, default=generate_random_slug)
    title = models.CharField(max_length=150)
    desc = models.CharField(max_length=600)
    create_at = models.DateTimeField(auto_now=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="video")
    is_published = models.BooleanField(default=False)
    watch = models.IntegerField(default=0)
    url_photo = models.URLField(max_length=500)
    url_video = models.URLField()
    url_video_240 = models.URLField(blank=True, null=True)
    url_video_360 = models.URLField(blank=True, null=True)
    url_video_720 = models.URLField(blank=True, null=True)
    url_video_1080 = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

    @property
    def like_count(self):
        return self.votes.filter(value=1).count()

    @property
    def dislike_count(self):
        return self.votes.filter(value=-1).count()


class PlayList(models.Model):
    ACCESS_CHOICES = (
        (1, "Public"),
        (2, "Unlisted"),
        (3, "Private"),
    )

    slug = models.SlugField(unique=True, null=True, blank=True, default=generate_random_slug)
    name = models.CharField(max_length=150,)
    access = models.IntegerField(choices=ACCESS_CHOICES, default=3)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    videos = models.ManyToManyField(Video, blank=True, related_name="playlist")



class Vote(models.Model):
    VOTE_CHOICE = (
        (1, "like"),
        (-1, "dislike")
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name="votes")
    value = models.SmallIntegerField(choices=VOTE_CHOICE)

    class Meta:
        unique_together = ('user', 'video')


class Notificated(models.Model):
    user = models.ForeignKey(User, related_name="user_notif", on_delete=models.CASCADE)
    notificated = models.TextField()
    from_user = models.ForeignKey(User, related_name="sent_notifications", null=True, blank=True, on_delete=models.SET_NULL)
    is_read = models.BooleanField(default=False)
    notificated_count = models.IntegerField()
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Data")

    def __str__(self):
        return f"Notification for {self.user.username}: {self.notificated[:20]}"


class WatchLater(models.Model):
    user = models.ForeignKey(User, related_name="user_video", on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    count_watch = models.IntegerField(default=0)
    added_at = models.DateTimeField(auto_now_add=True, verbose_name="Data")

    class Meta:
        unique_together = ("user", "video")
        ordering = ["-added_at"]

    def __str__(self):
        return f"{self.user.username} → {self.video.title}"


class LikesVideo(models.Model):
    user = models.ForeignKey(User, related_name="likeu_video", on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    count_likes = models.IntegerField(default=0)
    added_at = models.DateTimeField(auto_now_add=True, verbose_name="Data")

    def __str__(self):
        return str(self.count_likes)

class CommentsVideo(models.Model):
    slug = models.SlugField(unique=True, null=True, blank=True, default=generate_random_slug)
    user = models.ForeignKey(User, related_name="user_coment", on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    reply_to_comment = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True,related_name='replies')
    text = models.TextField(max_length=1500)
    create_at = models.DateTimeField(auto_now_add=True)

    @property
    def like_count(self):
        return self.votes.filter(value=1).count()

    @property
    def dislike_count(self):
        return self.votes.filter(value=-1).count()

    def __str__(self):
        return self.text


class VoteForComment(models.Model):
    VOTE_CHOICES = (
        (1, 'Like'),
        (-1, 'Dislike'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(CommentsVideo, on_delete=models.CASCADE, related_name='votes')
    value = models.SmallIntegerField(choices=VOTE_CHOICES)

    class Meta:
        unique_together = ('user', 'comment')


class LikesComment(models.Model):
    user = models.ForeignKey(User, related_name="likeu_comment", on_delete=models.CASCADE)
    comment = models.ForeignKey(CommentsVideo, on_delete=models.CASCADE)
    count_likes = models.IntegerField(default=0)
    added_at = models.DateTimeField(auto_now_add=True, verbose_name="Data")

    def __str__(self):
        return str(self.count_likes)

youtube/views/dislike_like_views.py
from django.shortcuts import redirect, get_object_or_404
from youtube.models import Video, Vote, LikesVideo, CommentsVideo, VoteForComment, LikesComment
from youtube.notification_system import add_notification

def like_video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    vote, created = Vote.objects.get_or_create(user=request.user,
                                               video=video)
    if vote.value == 1:
        vote.delete()
        vote.save()
    else:
        vote.value = 1
        vote.save()

    return redirect("video_detail", slug=slug)



def dislike_video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    vote, created = Vote.objects.get_or_create(user=request.user,
                                               video=video)
    if vote.value == -1:
        vote.delete()
        vote.save()
    else:
        vote.value = -1
        vote.save()

    return redirect("video_detail", slug=slug)


def post_vote(request, slug, value):
    video = get_object_or_404(Video, slug=slug)
    user = request.user

    if value not in["1", "-1"]:
        return redirect("video_detail", slug=slug)

    value = int(value)
    try:
        vote = Vote.objects.get(user=user, video=video)

        if vote.value == value:
            vote.delete()
        else:
            vote.value = value
            vote.save()
    except Vote.DoesNotExist:
        Vote.objects.create(user=user, video=video, value=value)

    if value == 1:
        existing_entry = LikesVideo.objects.filter(user=request.user, video=video)
        if existing_entry.exists():
            existing_entry.delete()
        else:
            LikesVideo.objects.create(user=request.user, video=video)

    if video.autor != user:
        action = "лайкнув" if value == 1 else "дизлайкнув"
        add_notification(
            user=video.autor,
            from_user=user,
            message=f"{action} ваш пост.",
            not_count=1
        )

    return redirect("video_detail", slug=slug)






def comment_vote(request, comment_id, value):
    user = request.user
    comment = get_object_or_404(CommentsVideo, id=comment_id)

    if value not in ["1", "-1"]:
        return redirect("video_detail", slug=comment.video.slug)

    value = int(value)

    vote, created = VoteForComment.objects.get_or_create(
        user=user, comment=comment, defaults={"value": value}
    )

    if not created and vote.value == value:
        vote.delete()
    else:
        vote.value = value
        vote.save()

    existing_like = LikesComment.objects.filter(user=user, comment=comment)
    if value == 1:
        if existing_like.exists():
            existing_like.delete()
        else:
            LikesComment.objects.create(user=user, comment=comment)
    else:
        existing_like.delete()

    if comment.user != user:
        action = "liked" if value == 1 else "disliked"
        add_notification(
            user=comment.user,
            from_user=user,
            message=f"{action} your comment.",
            not_count=1
        )

    return redirect("video_detail", slug=comment.video.slug)



def comment_like(request, comment_id):
    user = request.user
    comment = get_object_or_404(CommentsVideo, id=comment_id)

    vote, created = VoteForComment.objects.get_or_create(user=user, comment=comment)
    if vote.value == 1:
        vote.delete()
    else:
        vote.value = 1
        vote.save()

    like_obj, created_like = LikesComment.objects.get_or_create(user=user, comment=comment)
    if not created_like:
        like_obj.delete()

    if comment.user != user:
        add_notification(
            user=comment.user,
            from_user=user,
            message="liked your comment.",
            not_count=1
        )

    return redirect("video_detail", slug=comment.video.slug)



def comment_dislike(request, comment_id):
    user = request.user
    comment = get_object_or_404(CommentsVideo, id=comment_id)

    vote, created = VoteForComment.objects.get_or_create(user=user, comment=comment)
    if vote.value == -1:
        vote.delete()
    else:
        vote.value = -1
        vote.save()

    LikesComment.objects.filter(user=user, comment=comment).delete()

    if comment.user != user:
        add_notification(
            user=comment.user,
            from_user=user,
            message="disliked your comment.",
            not_count=1
        )

    return redirect("video_detail", slug=comment.video.slug)

youtube/views/notificate_views.py
from django.shortcuts import render


def notificated_view(request):
    unread_before = list(request.user.user_notif.filter(is_read=False).values_list('id', flat=True))

    request.user.user_notif.filter(is_read=False).update(is_read=True)
    notifications = request.user.user_notif.order_by("-create_at")
    context = {
        'notifications': notifications,
        'newly_read_ids': unread_before,
    }
    return render(request, "movies/notification.html", context)

youtube/views/profile_view.py
from django.views.generic import DetailView
from youtube.models import Video, Autor


class Profile(DetailView):
    model = Autor
    context_object_name = "autor"
    template_name = "movies/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs["slug"]
        video = Video.objects.filter(autor__autor__slug=slug)
        context["videos"] = video
        context["videos_count"] = context["videos"].count()

        return context

class ProfileSettings(DetailView):
    model = Autor
    context_object_name = "autor_settings"
    template_name = "movies/profile_settings.html"

youtube/views/registration_view.py
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render
from django.contrib import messages
from youtube.forms import LoginForm, RegistrationForm
from youtube.models import Autor
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


def user_login(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, "Success Login!")
            return redirect("home")
    else:
        form = LoginForm()

    context = {"title": "Login", "form": form}
    return render(request, "movies/registration/login.html", context)

def user_logout(request):
    logout(request)
    messages.success(request, "Success Logout!")
    return redirect("home")


def register(request):
    if request.method == "POST":
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Success Registration!")
            return redirect("login")
    else:
        form = RegistrationForm()

    context = {
        "title": "Registration",
        "form": form,
    }
    return render(request, "movies/registration/register.html", context)



@receiver(post_save, sender=User)
def create_autor(sender, instance, created, **kwargs):
    if created:
        Autor.objects.create(user=instance, nickname=instance.username, pseudonym=f"@{instance.username}")

youtube/templates/movies/add_playlist_modal.html
<h6>🎵 Add "{{ video.title }}" to playlist</h6>

{% if user.playlist_set.exists %}
<ul class="list-group mb-3">
    {% for pl in user.playlist_set.all %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        {{ pl.name }}
        {% if video in pl.videos.all %}
        <a href="{% url 'delete_from_play_list' pl.slug video.slug %}"
           class="btn btn-sm btn-outline-danger remove-video-link">
            Remove
        </a>
        {% else %}
        <a href="{% url 'add_from_play_list' pl.slug video.slug %}"
           class="btn btn-sm btn-outline-success add-video-link">
            Add
        </a> {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<p class="text-muted">You have no playlists yet.</p>
{% endif %}

<form method="post" class="mt-3 add-to-playlist-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary w-100 mt-2">Add to playlist</button>
</form>

youtube/templates/movies/createvideo.html
{% extends 'movies/base.html' %}

{% block content %}

<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-dark" type="submit">Login</button>
</form>


{% endblock %}

youtube/templates/movies/index.html
{% extends 'movies/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'video/index.css' %}">

<div class="row">
    {% for video in videos %}
    <div class="col-md-4 mb-4">
        <div class="card h-100 shadow-sm position-relative">
            <a href="{% url 'video_detail' video.slug %}">
                <img src="{{ video.url_photo }}" class="card-img-top" alt="{{ video.title }}">
            </a>
            <div class="card-body">
                <h5 class="card-title">{{ video.title }}</h5>
                <p class="card-text">{{ video.desc }}</p>
            </div>
         {% include "movies/component/dropdown.html" %}
        </div>
    </div>
    {% empty %}
    <p>No videos found.</p>
    {% endfor %}
</div>

         {% include "movies/component/playlist.html" %}

<script src="{% static 'js/share_video.js' %}"></script>
<script src="{% static 'js/add_playlist_modal.js' %}"></script>
{% endblock %}

youtube/templates/movies/notification.html
{% extends 'movies/base.html' %}
{% block title %}Notifications{% endblock %}

{% block content %}
<h1 class="mb-4">Notifications</h1>

{% if notifications %}
{% for notif in notifications %}
<div class="card mb-3 p-3
                {% if notif.id in newly_read_ids %}just-read{% endif %}
                {% if not notif.is_read %}border-primary{% endif %}">
    <div class="d-flex justify-content-between align-items-center">
        <div>
            {% if notif.from_user %}
            <a href="{% url 'profile' notif.from_user.autor.slug %}"
               class="me-2 {% if not notif.is_read %}fw-bold{% endif %}"
               style="color: black; font-weight: bold; text-decoration: none;">
                {{ notif.from_user.username }}
            </a>

            {% else %}
            <span class="{% if not notif.is_read %}fw-bold{% endif %} me-2">System</span>
            {% endif %}
            <span class="{% if not notif.is_read %}fw-bold{% endif %}">
            {{ notif.notificated }}
          </span>
        </div>
        <div class="text-muted small">
            {{ notif.create_at|date:"d M Y H:i" }}
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<div class="alert alert-info">No notifications</div>
{% endif %}

<style>
    .just-read {
        border: 2px solid red !important;
        box-shadow: 0 0 10px rgba(255, 0, 0, 0.6);
    }
</style>
{% endblock %}

youtube/templates/movies/playlist_success.html
<div class="text-center p-3">
  <p class="text-success fs-5">✅ Playlist created successfully!</p>
</div>

youtube/templates/movies/video_detail.html
{% extends 'movies/base.html' %}
{% load static %}

{% block sidebar_class %}d-none{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'video/video_detail.css' %}">

<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-lg-8">
            <div class="video-player rounded shadow-sm overflow-hidden mb-3">
                <video id="custom-video"
                       src="{% url 'stream_video' video.slug %}"
                       preload="metadata"
                       playsinline
                       controlslist="nodownload nofullscreen noremoteplayback"
                       disablepictureinpicture>
                </video>
            </div>

            <h3 class="fw-bold mb-2">{{ video.title }}</h3>

            <div class="d-flex align-items-center justify-content-between mb-3">
                <div>
                    <p class="mb-0 text-muted small">
                        {{ video.autor.username }} • {{ video.create_at|date:"F j, Y" }}
                    </p>
                    <div class="d-flex align-items-center gap-3 my-3">
                        <span class="text-muted small">👁️ {{ video.watch }} views</span>

                        <form method="post" action="{% url 'video_vote' video.slug 1 %}" class="m-0 p-0">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-sm d-flex align-items-center gap-1 {% if user_vote == 1 %}btn-success{% else %}btn-outline-success{% endif %}">
                                👍 <span class="fw-bold">{{ like_count }}</span>
                            </button>
                        </form>

                        <form method="post" action="{% url 'video_vote' video.slug -1 %}" class="m-0 p-0">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-sm d-flex align-items-center gap-1 {% if user_vote == -1 %}btn-danger{% else %}btn-outline-danger{% endif %}">
                                👎 <span class="fw-bold">{{ dislike_count }}</span>
                            </button>
                        </form>
                    </div>
                </div>

                {% if request.user.autor and request.user == video.autor %}
                    <a href="{% url 'edit_video' video.slug %}" class="btn btn-info btn-sm px-3" role="button">
                        Edit video
                    </a>
                {% elif subscription_status == "subscribed" %}
                    <a href="{% url 'remove_subscribers' video.autor.pk %}" class="btn btn-info btn-sm px-3" role="button">
                        You Subscribe
                    </a>
                {% elif subscription_status == "not_subscribed" %}
                    <a href="{% url 'add_subscribers' video.autor.pk %}" class="btn btn-danger btn-sm px-3" role="button">
                        Subscribe
                    </a>
                {% endif %}
            </div>

            <hr>

            <div class="mb-4">
                <h6 class="fw-semibold">Description</h6>
                <p class="text-light bg-dark p-3 rounded">{{ video.desc }}</p>
            </div>

            <div class="comments-section mt-5">
                <h4 class="fw-bold mb-4">💬 Comments</h4>

                <form method="post" action="{% url 'add_comment' video.slug %}" class="mb-4">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form_comm.text }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-2 px-4">Add</button>
                </form>

                <hr class="my-4">

                {% for comment in video.commentsvideo_set.all %}
                {% if not comment.reply_to_comment %}
                <div class="comment-item mb-3 p-3 rounded shadow-sm" style="background-color: #f8f9fa;">
                    <div class="d-flex align-items-center mb-2">
                        <div class="avatar bg-secondary text-white rounded-circle d-flex justify-content-center align-items-center me-3"
                             style="width:40px; height:40px;">
                            {{ comment.user.username|first|upper }}
                        </div>
                        <div>
                            <strong>{{ comment.user.username }}</strong><br>
                            <small class="text-muted">{{ comment.create_at|date:"d.m.Y H:i" }}</small>
                        </div>
                    </div>

                    <div class="ps-5">
                        <p class="mb-2">{{ comment.text }}</p>

                        <div class="d-flex align-items-center gap-2 mb-2">
                            <form method="post" action="{% url 'comment_vote' comment.id 1 %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-outline-success">
                                    👍 {{ comment.like_count }}
                                </button>
                            </form>
                            <form method="post" action="{% url 'comment_vote' comment.id -1 %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-outline-danger">
                                    👎 {{ comment.dislike_count }}
                                </button>
                            </form>
                            <button class="btn btn-sm btn-outline-primary reply-btn" data-comment-slug="{{ comment.slug }}">
                                Reply
                            </button>
                        </div>

                        <div class="reply-form-container mt-2"></div>

                        {% for reply1 in comment.replies.all %}
                        <div class="comment-item mt-2 p-2 rounded shadow-sm ms-4" style="background-color: #e9ecef;">
                            <div class="d-flex align-items-center mb-1">
                                <div class="avatar bg-secondary text-white rounded-circle d-flex justify-content-center align-items-center me-3"
                                     style="width:35px; height:35px;">
                                    {{ reply1.user.username|first|upper }}
                                </div>
                                <div>
                                    <strong>{{ reply1.user.username }}</strong><br>
                                    <small class="text-muted">{{ reply1.create_at|date:"d.m.Y H:i" }}</small>
                                </div>
                            </div>

                            <div class="ps-4">
                                <p class="mb-2"><strong>@{{ reply1.reply_to_comment.user.username }}</strong> {{ reply1.text }}</p>

                                <div class="d-flex align-items-center gap-2 mb-1">
                                    <form method="post" action="{% url 'comment_vote' reply1.id 1 %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-sm btn-outline-success">
                                            👍 {{ reply1.like_count }}
                                        </button>
                                    </form>
                                    <form method="post" action="{% url 'comment_vote' reply1.id -1 %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-sm btn-outline-danger">
                                            👎 {{ reply1.dislike_count }}
                                        </button>
                                    </form>

                                    <button class="btn btn-sm btn-outline-primary reply-btn" data-comment-slug="{{ reply1.slug }}">
                                        Reply
                                    </button>
                                </div>

                                <div class="reply-form-container mt-2"></div>

                                {% for reply2 in reply1.replies.all %}
                                <div class="comment-item mt-2 p-2 rounded shadow-sm ms-4" style="background-color: #dee2e6;">
                                    <div class="d-flex align-items-center mb-1">
                                        <div class="avatar bg-secondary text-white rounded-circle d-flex justify-content-center align-items-center me-3"
                                             style="width:35px; height:35px;">
                                            {{ reply2.user.username|first|upper }}
                                        </div>
                                        <div>
                                            <strong>{{ reply2.user.username }}</strong><br>
                                            <small class="text-muted">{{ reply2.create_at|date:"d.m.Y H:i" }}</small>
                                        </div>
                                    </div>
                                    <div class="ps-4">
                                        <p class="mb-2"><strong>@{{ reply2.reply_to_comment.user.username }}</strong> {{ reply2.text }}</p>

                                        <div class="d-flex align-items-center gap-2">
                                            <form method="post" action="{% url 'comment_vote' reply2.id 1 %}">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-sm btn-outline-success">
                                                    👍 {{ reply2.like_count }}
                                                </button>
                                            </form>
                                            <form method="post" action="{% url 'comment_vote' reply2.id -1 %}">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-sm btn-outline-danger">
                                                    👎 {{ reply2.dislike_count }}
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
                {% empty %}
                <p class="text-muted">No comments yet. Be the first!</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/video_details.js' %}"></script>
{% endblock %}